# Generated by Django 4.2.8 on 2025-04-27 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_classroom_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'db_table': 'group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Заняття', 'verbose_name_plural': 'Заняття'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кількість пар на тиждень'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('5', '5 курс'), ('6', '6 курс')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.subject'),
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понеділок'), ('tue', 'Вівторок'), ('wed', 'Середа'), ('thu', 'Четвер'), ('fri', 'Пʼятниця')], max_length=3)),
                ('time_slot', models.PositiveSmallIntegerField(choices=[(1, '08:00–09:00'), (2, '10:00–11:00'), (3, '12:00–13:00'), (4, '14:00–15:00')])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.classroom')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson')),
            ],
            options={
                'unique_together': {('day', 'time_slot', 'classroom')},
            },
        ),
    ]
