# Generated by Django 4.2.8 on 2025-04-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_group_subject_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклади'},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='day',
            field=models.CharField(choices=[('mon', 'Понеділок'), ('tue', 'Вівторок'), ('wed', 'Середа'), ('thu', 'Четвер'), ('fri', 'П’ятниця')], max_length=3),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '08:00-09:00'), (2, '10:00-11:00'), (3, '12:00-13:00'), (4, '14:00-15:00')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together={('group', 'day', 'time_slot')},
        ),
        migrations.AlterModelTable(
            name='scheduleentry',
            table='schedule_entry',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='classroom',
        ),
    ]
