# Generated by Django 4.2.8 on 2025-04-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_scheduleentry_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.classroom'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='day_of_week',
            field=models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ('Пʼятниця', 'Пʼятниця')], default='Понеділок', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='lesson_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson'),
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='day',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='time_slot',
        ),
    ]
