# Generated by Django 4.2.8 on 2025-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_scheduleentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Практична', 'Практична'), ('Лекція', 'Лекція'), ('Семінар', 'Семінар'), ('Лабораторна', 'Лабораторна')], default='Практична', max_length=20, verbose_name='Тип заняття'),
        ),
    ]
