# Generated by Django 4.2.8 on 2025-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Практична', 'Практична'), ('Лекція', 'Лекція'), ('Семінар', 'Семінар'), ('Лабораторна', 'Лабораторна'), ('Консультація', 'Консультація')], default='Практична', max_length=20, verbose_name='Тип заняття'),
        ),
    ]
