# Generated by Django 4.2.8 on 2025-04-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.semester'),
        ),
    ]
