# Generated by Django 4.2.8 on 2025-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_scheduleentry_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='semester',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('m1', '1 курс маг.'), ('m2', '2 курс маг.')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Практична', 'Практична'), ('Лекція', 'Лекція'), ('Семінар', 'Семінар'), ('Лабораторна', 'Лабораторна')], default='Практична', max_length=20, verbose_name='Тип заняття'),
        ),
    ]
