# Generated by Django 4.2.8 on 2025-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_scheduleentry_semester_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Практична', 'Практична'), ('Лекція', 'Лекція'), ('Семінар', 'Семінар'), ('Лабораторна', 'Лабораторна'), ('Консультація', 'Консультація')], default='Практична', max_length=20, verbose_name='Тип заняття'),
        ),
    ]
