# Generated by Django 4.2.8 on 2025-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку'),
        ),
    ]
