# Generated by Django 4.2.8 on 2025-05-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_lesson_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('m1', '1 курс маг.'), ('m2', '2 курс маг.')], max_length=2, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.semester', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.teacher', verbose_name='Викладач'),
        ),
    ]
