# Generated by Django 4.2.8 on 2025-05-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_lesson_course_alter_lesson_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Місткість'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(max_length=100, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва кафедри'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва групи'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер семестру'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(max_length=20, verbose_name='Навчальний рік'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва предмету'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Науковий ступінь'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.department', verbose_name='Належність до кафедри'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Посада'),
        ),
    ]
