# Generated by Django 4.2.8 on 2025-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_classroom_capacity_alter_classroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='week_type',
            field=models.CharField(choices=[('even', 'Парний тиждень'), ('odd', 'Непарний тиждень'), ('both', 'Обидва тижні')], default='both', max_length=5),
        ),
    ]
