# Generated by Django 4.2.8 on 2025-05-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_lesson_week_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='week_type',
            field=models.CharField(choices=[('even', 'Парний'), ('odd', 'Непарний'), ('both', 'Щотижня')], default='both', max_length=10),
        ),
    ]
