# Generated by Django 4.2.8 on 2025-05-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_scheduleentry_week_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(blank=True, default='Запрошений викладач', max_length=100, verbose_name='Факультет'),
        ),
    ]
