# Generated by Django 4.2.8 on 2025-05-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_alter_department_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(max_length=100, verbose_name='Факультет'),
        ),
    ]
