# Generated by Django 4.2.8 on 2025-05-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_alter_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.semester'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
