# Generated by Django 4.2.8 on 2025-05-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_scheduleentry_semester_scheduleentry_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='week',
        ),
    ]
