# Generated by Django 4.2.8 on 2025-05-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_remove_scheduleentry_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.semester'),
        ),
    ]
