# Generated by Django 4.2.8 on 2025-05-09 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_scheduleentry_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ('Пʼятниця', 'Пʼятниця'), ('Субота', 'Субота')], default='Понеділок', max_length=10)),
                ('lesson_number', models.PositiveIntegerField(null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.classroom')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.semester')),
            ],
            options={
                'verbose_name': 'Сесія',
                'verbose_name_plural': 'Сесії',
                'db_table': 'session_entry',
            },
        ),
    ]
