# Generated by Django 4.2.8 on 2025-05-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_sessionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('m1', '1 курс маг.'), ('m2', '2 курс маг.')], max_length=2, verbose_name='Курс')),
                ('control_type', models.CharField(choices=[('Залік', 'Залік'), ('Екзамен', 'Екзамен')], default='Залік', max_length=20, verbose_name='Тип контролю')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schedule.classroom', verbose_name='Аудиторія')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Група')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.teacher', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Залік/Екзамен',
                'verbose_name_plural': 'Залік/Екзамен',
                'db_table': 'session',
            },
        ),
        migrations.DeleteModel(
            name='SessionEntry',
        ),
    ]
