from django.urls import path
from . import views
from .views import (AddDepartment, AddTeacher, About, Contacts, TeacherListView, \
                    DepartmentListView, TeacherDeleteView, DepartmentDeleteView,
                    AddAudience, \
                    AudienceListView, AudienceDeleteView, TeacherUpdateView, \
                    DepartmentUpdateView, AudienceUpdateView, AddLesson,
                    LessonDeleteView,
                    LessonUpdateView, AddGroup, GroupListView,
                    AddGroup, GroupListView,
                    GroupDeleteView, GroupUpdateView, SubjectListView,
                    AddSubject, SubjectDeleteView, SubjectUpdateView,
                    AddSemester, SemesterListView, SemesterDeleteView,
                    SemesterUpdateView, LessonListView, generate_schedule,
                    schedule_view, delete_lesson, add_lesson_view, edit_lesson_view )

urlpatterns = [
    path('', views.home, name='home'),
    path('add_department/', AddDepartment.as_view(), name='add_department'),
    path('add_teacher/', AddTeacher.as_view(), name='add_teacher'),
    path('add_audience/', AddAudience.as_view(), name='add_audience'),
    path('add_lesson/', AddLesson.as_view(), name='add_lesson'),
    path('about/', About.as_view(), name='about'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('teachers/', TeacherListView.as_view(), name='teacher_list'),
    path('departments/', DepartmentListView.as_view(), name='department_list'),
    path('audiences/', AudienceListView.as_view(), name='audience_list'),
    path('teachers/<int:pk>/delete/', TeacherDeleteView.as_view(), name='teacher_delete'),
    path('departments/<int:pk>/delete/', DepartmentDeleteView.as_view(),
         name='department_delete'),
    path('audiences/<int:pk>/delete/', AudienceDeleteView.as_view(),
         name='audience_delete'),
    path('lessons/<int:pk>/delete/', LessonDeleteView.as_view(),
         name='lesson_delete'),
    path('lessons/<int:pk>/edit/', LessonUpdateView.as_view(),
         name='lesson_edit'),
    path('teachers/<int:pk>/edit/', TeacherUpdateView.as_view(), name='teacher_edit'),
    path('departments/<int:pk>/edit/', DepartmentUpdateView.as_view(),
         name='department_edit'),
    path('audiences/<int:pk>/edit/', AudienceUpdateView.as_view(),
         name='audience_edit'),
    path('lessons/<int:pk>/edit/', LessonUpdateView.as_view(),
         name='lesson_edit'),
    path('add_group/', AddGroup.as_view(), name='add_group'),
    path('groups/', GroupListView.as_view(), name='group_list'),
    path('groups/<int:pk>/delete/', GroupDeleteView.as_view(),
         name='group_delete'),
    path('groups/<int:pk>/edit/', GroupUpdateView.as_view(),
         name='group_edit'),
    path('subjects/', SubjectListView.as_view(), name='subject_list'),
    path('add_subject/', AddSubject.as_view(), name='add_subject'),
    path('subjects/<int:pk>/delete/', SubjectDeleteView.as_view(),
         name='subject_delete'),
    path('subjects/<int:pk>/edit/', SubjectUpdateView.as_view(),
         name='subject_edit'),
    path('add_semester/', AddSemester.as_view(), name='add_semester'),
    path('semesters/', SemesterListView.as_view(), name='semester_list'),
    path('semesters/<int:pk>/delete/', SemesterDeleteView.as_view(),
         name='semester_delete'),
    path('semesters/<int:pk>/edit/', SemesterUpdateView.as_view(),
         name='semester_edit'),
    path('lessons/', LessonListView.as_view(), name='lesson_list'),
    path('generate/', generate_schedule, name='generate_schedule'),
    path('schedule/', schedule_view, name='schedule_view'),
    path('schedule/<int:lesson_id>/delete/', views.delete_lesson, name='delete_lesson'),
    path('schedule/add/', views.add_lesson_view,
         name='add_lesson_entry'),
    path('export_excel', views.export_schedule_excel,
         name='export_schedule_excel'),
    path('schedule/<int:entry_id>/edit', views.edit_lesson_view,
         name='edit_lesson_entry'),
]
